### PR TITLE
Add RPC endpoint for cid rank proofs

### PR DESCRIPTION
**Pull request by janus**
Add RPC endpoint for cid rank proofs

### CODE REVIEW

**Comment by litvintech** [comment]
@janus tested yesterday, didn't work as is
Are you tried to setup local dev network and put links and then take rank/proofs from endpoint?

**Comment by janus** [comment]
@litvintech , Link to how to set up local dev network.
And could you comment on the other issues that I raised

**Comment by litvintech** [comment]
> @litvintech , Link to how to set up local dev network.
> And could you comment on the other issues that I raised

https://github.com/cybercongress/cyberd/blob/91aa7509b8c06af6ca4e99ac1f57c139ea4e0a17/docs/help/setup_dev_env.md

**Comment by litvintech** [comment]
@janus please PR to branch 0.1.5, but before you need swith to it

**Comment by litvintech** [comment]
merged in https://github.com/cybercongress/cyberd/pull/355

**Pull request closed without merging**
