### PR TITLE
DISCUSS: Chain params for 0.1.1 network

### PR DESCRIPTION
**Pull request by hleb-albau**
https://github.com/cybercongress/cyberd/blob/chain_params/docs/overview.md
Here, I collect all params into a single place and create a small description about cosmos-sdk modules flow. Please, ask as many questions as you can, we will improve this doc.

Also, here I propose values on params.
I suggest increasing block size to 5s. Currently, on a small network, it takes about half a day to catch up the empty chain.

### CODE REVIEW

**Comment by xhipster** [comment]
146 - Because of [Dunbars number](https://en.wikipedia.org/wiki/Dunbar%27s_number)
1 second - Because with 5 seconds we will have pretty slow thing

**Comment by hleb-albau** [comment]
> 146 - Because of [Dunbars number](https://en.wikipedia.org/wiki/Dunbar%27s_number)
> 1 second - Because with 5 seconds we will have pretty slow thing

1. Dunbars number not really related to validators problems. Cosmos-hub will slightly increate year by year validator set, starting 100 to 200 by 10 years.
2. We should choose the trade-off between validator requirements and block generation speed. Currently, if we choose 1 sec, then all validators should have a very good internet connection to not miss block signing(by miss I mean not being offline, but just delayed sign). There is **MinSignedPerWindow** param, that set minimum successful block signs for **SignedBlocksWindow**. With unstable validators(our case right now), we should set it to higher value, say **2/3**. In other case, network will eventually stop, cuz there are no **2/3** block signs. If we chouse high **MinSignedPerWindow**, than regular validators will be **jailed** frequently(we already see it on 0.1.0 testnet). That can scare away initial intusiasts. Guys from polka, said that for more than 20 valdiator, currently it is not really possible to have stable network with 1 sec  block for a long period.

**Comment by xhipster** [comment]
Guys from polka, said that for more than 20 valdiator, currently it is not really possible to have stable network with 1 sec block for a long period.

It's because the network runs without money

**Comment by xhipster** [comment]
Overall, I would discus with Valera first some principles of the network we are building. They define parametrs

**Comment by hleb-albau** [comment]
@arturalbov Check it, please.

**Pull request merged**
